---
title: "Participant characteristics"
---

```{r results='asis'}
if(!file.exists("data/private/subject_meta.csv")){
 cat("**The data/private/subject_meta.csv required for this page is not available
 due to privacy concerns. Skipping execution...**")
  knitr::knit_exit()
}
```

```{r fig.width=8,fig.height=4}
source("code/setup.R")
```

# Importing BPD/CNTRL metadata

Bringing in some other metadata for the subjects (will not show publicly).

```{r}
# Import actigraphy (sleep)
act <- read_rds("output/actigraphy_cosinor.rds")

# Metadata
# Not shown for privacy
dfu <- read_csv("data/private/subject_meta.csv")

# Weight oscillations
weightCS <- rbind(
  read_rds("output/body_weight/weight_S-cosinor_dx1.rds") |> mutate(dx = 1),
  read_rds("output/body_weight/weight_S-cosinor_dx0.rds") |> mutate(dx = 0)
)

# Merging metadata
allmeta <-
  rbind(
    dfu |>
      select(
        subject, dx, height_cm, weight_kg, bmi,
        sleeping_per_day_hours, psqi_score,
        exercise_per_week_hours,
        age, ymrs_sum
      ) |>
      pivot_longer(height_cm:last_col()),
    act |>
      mutate(dx = as.numeric(group == "BPD")) |>
      ungroup() |>
      select(subject, dx,
        act_acro = acrophase,
        act_amp = amplitude,
        act_mesor = mesor, sleep_dur
      ) |>
      pivot_longer(act_acro:last_col()),
    weightCS |>
      mutate(acro = ifelse(acrophase < 12, acrophase + 24, acrophase)) |>
      select(subject, dx,
        weight_acro = acro,
        weight_amp = amplitude,
        weight_mesor = mesor
      ) |>
      pivot_longer(weight_acro:last_col())
  ) |>
  mutate(name = fct_inorder(name)) |>
  mutate(dx = dx2lab(dx))
```

Performing group-wise tests

```{r}
statab <-
  allmeta |>
  group_by(dx, name) |>
  summarize(
    mu = mean(value, na.rm = T),
    sd = sd(value, na.rm = T),
    n_missing = sum(is.na(value))
  ) |>
  mutate(txt = paste0(formatC(mu, digits = 2), " (", formatC(sd, digits = 2), ") ", ifelse(n_missing == 0, "", n_missing))) |>
  select(dx, name, txt) |>
  filter(!grepl("std", name)) |>
  pivot_wider(names_from = dx, values_from = txt) |>
  full_join(allmeta |>
    group_by(name) |>
    nest() |>
    mutate(res = map(data, function(x) {
      if (all(is.na(x$value[x$dx == "CNTRL"]))) {
        return(NA)
      }
      t.test(
        x$value[x$dx == "BPD"],
        x$value[x$dx == "CNTRL"]
      ) |> tidy()
    })) |> unnest(res) |>
    filter(!grepl("std", name)) |>
    select(
      -data, -estimate, -estimate1, -estimate2,
      -c(parameter:alternative)
    )) |>
  # Input by hand
  rbind(data.frame(
    name = "Caffeine", BPD = "8/8", CNTRL = "12/16",
    p.value = fisher.test(
      c(
        rep(F, 0), rep(T, 8),
        rep(T, 12), rep(F, 4)
      ),
      c(rep(T, 8), rep(F, 16))
    )$p.value,
    statistic = fisher.test(
      c(
        rep(F, 0), rep(T, 8),
        rep(T, 12), rep(F, 4)
      ),
      c(rep(T, 8), rep(F, 16))
    )$estimate
  )) |>
  rbind(data.frame(
    name = "Smoking", BPD = "4/8", CNTRL = "1/16",
    p.value = fisher.test(
      c(
        rep(F, 4), rep(T, 4),
        rep(T, 1), rep(F, 15)
      ),
      c(rep(T, 8), rep(F, 16))
    )$p.value,
    statistic = fisher.test(
      c(
        rep(F, 4), rep(T, 4),
        rep(T, 1), rep(F, 15)
      ),
      c(rep(T, 8), rep(F, 16))
    )$estimate
  ))
statab
```


# Table 1 | characteristics

```{r}
library(flextable)
tab <-
  statab |>
  mutate(statistic = formatC(statistic, digits = 2)) |>
  mutate(p.value = formatC(p.value, digits = 2)) |>
  # Rearrange
  select(name, CNTRL, BPD, `t or OR` = statistic, p.value) |> # slice(6:20)
  mutate(name = c(
    "age" = "Age",
    "weight_kg" = "Weight [kg]",
    "height_cm" = "Height [cm]",
    "bmi" = "BMI",
    "Caffeine" = "Consumed caffeine",
    "Smoking" = "Is smoker",
    "act_acro" = "Actigraphy acrophase [hr]",
    "act_amp" = "Actigraphy amplitude",
    "act_mesor" = "Actigraphy MESOR",
    "sleep_dur" = "Actigraphy time-in-bed [hr]",
    "sleeping_per_day_hours" = "Sleep duration [hr/day]",
    "psqi_score" = "Sleep quality [PSQI]",
    "exercise_per_week_hours" = "Exercise [hr/week]",
    "weight_acro" = "Body weight acrophase [hr]",
    "weight_amp" = "Body weight diurnal amplitude [kg]",
    "weight_mesor" = "Body weight MESOR [kg]",
    "ymrs_sum" = "YMRS"
  )[as.character(name)]) |>
  slice(7, 2, 1, 3, 16, 17, 9:11, 12, 4, 5, 6, 13:15, 8) |>
  rename(Characteristic = name)

tab |>
  flextable() |>
  flextable::autofit()

# For post process
write_csv(tab, "output/table_1.csv")
```
